const language = [
  //English
  {
    app_title: "Gestimmo",
    step1: 'Step 1: Advertisement',
    main_info: 'Main Information',
    title_of_ad: 'Title of Ad',
    description: 'Description',
    country: 'Country',
    postcode: 'Postcode',
    street_and_house_number: 'Street and House number',
    details: 'Details',
    type_of_ownership: 'Type of Ownership',
    for_rent: 'For rent',
    for_sale: 'For sale',
    category: 'Category',
    surface: 'Surface',
    floor: 'Floor',
    rooms: 'Rooms',
    invalid_date_format: 'Invalid Date Format',
    price_type: 'Price Type',
    on_request: 'On request',
    price: 'Price',
    back: 'Back',
    next: 'Next',
    step2: 'Step 2: Extra Details',
    near: 'Near',
    proximity: 'Proximity',
    facilities: 'Facilities',
    outdoor_equipment: 'Outdoor Equipment',
    interior_equipment: 'Interior Equipment',
    other_equipment: 'Other Equipment',
    soils: 'Soils',
    exposition: 'Exposition',
    views: 'Views',
    sunshine: 'Sunshine',    
    step3: 'Step 3: Photos',
    drop_some_files_here: 'Drop some files here!',
    or: 'or',
    choose: 'Choose',
    step4: 'Step 4: Contact Information',
    full_name: 'Full Name',
    phone_number: 'Phone Number',
    email: 'Email',
    compleated_all_the_steps: 'You have completed all the steps!',
    upload_ads: 'Upload Ads',
    confirm: 'Confirm',
    you_can_continue_from_the_previous_state: 'You can continue from the previous state',
    yes: 'Yes',
    no: 'No',
    result: 'Result',
    load_more: 'Load more',
    type: 'Type',
    rent: 'Rent',
    buy: 'Buy',
    property: 'Property',
    city: 'City',
    floor: 'Floor',
    min: 'Min',
    max: 'Max',
    room: 'Room',
    canton: "Canton",
    availability: "Availability",
    from_date: "From Date",
    immediately: "Immediately",
    charge: "Charge",
    choose: "Choose",
    upload_changes: "Upload Changes",
    english_native: 'English',  
    french_native: 'Français',
    german_native: 'Deutsch',
    italian_native: 'Italiano',
    canton: 'Canton',
    profile: 'Profile',
    company:'Company',
    create_company:'create company',
    adress:'Address',
    basic_information:'Basic information',
    company_name:'Company name',
    additional_address:'Additional Address',
    inbox_email:'Inbox email address',
    short_name:'Short name for Inbox email address',
    additional_information:'Additional information',
    contact_information:'Contact Information',
    mobile_p:'Mobile phone',
    website:'Website',
    fax:'Fax',
    save_changes:'Save Changes',
    contacts:'Contacts',
    imp_exp:'Import/Export',
    new_contact:'New Contact',
    all:'All',
    filter:'Filter',
    marked:'Marked as deleted',
    attributes:'Attributes',
    b_atributes:'Building Attributes(optional)',
    more_photos:'More Photos',
    create_button:'Create',
    upload_txt:'Upload building photos here. If your building has multiple units, individual unit photos should be added at unit level(later step).',
    photo_property:'Property Photo',
    property_type:'Property Type',
    number_of_units:'Number of units you own',
    unit_identification:'Unit identification',
    add_new_property:'Add new property',
    my_property:'My Properties',
    pick_up:'Pick Up'


    
  },
  //French
  {
    app_title: "Gestimmo",
    step1: 'Étape 1: publicité',
    main_info: 'Informations principales',
    title_of_ad: 'Titre de l n\'annonce',
    description: 'La description...',
    country: 'Pays',
    postcode: 'Code postal',
    street_and_house_number: 'Rue et numéro de maison',
    details: 'Détails',
    type_of_ownership: 'Type de propriété',
    for_rent: 'A louer',
    for_sale: 'À vendre',
    category: 'Catégorie',
    surface: 'Surface',
    floor: 'Sol',
    rooms: 'Pièces',
    invalid_date_format: 'Format de date invalide',
    price_type: 'Type de prix',
    on_request: 'Sur demande',
    price: 'Prix',
    back: 'Retour',
    next: 'Prochain',
    step2: 'Étape 2: Détails supplémentaires',
    near: 'Près',
    proximity: 'Proximité',
    facilities: 'Installations',
    outdoor_equipment: 'Équipement de plein air',
    interior_equipment: 'Équipement intérieur',
    other_equipment: 'Autre équipement',
    soils: 'Les sols',
    exposition: 'Exposition',
    views: 'Des vues',
    sunshine: 'Ensoleillement',    
    step3: 'Étape 3: Photos',
    drop_some_files_here: 'Déposer des fichiers ici!',
    or: 'ou',
    choose: 'Choisir',
    step4: 'Étape 4: Coordonnées',
    full_name: 'Nom complet',
    phone_number: 'Numéro de téléphone',
    email: 'Email',
    compleated_all_the_steps: 'Vous avez terminé toutes les étapes!',
    upload_ads: 'Transférer des annonces',
    confirm: 'Confirmer',
    you_can_continue_from_the_previous_state: 'Vous pouvez continuer à partir de l n\'état précédent',
    yes: 'Oui',
    no: 'Non',
    result: 'résultat',
    load_more: 'Charger plus',
    type: 'Type',
    rent: 'Louer',
    buy: 'Acheter',
    property: 'Propriété',
    city: 'Ville',
    floor: 'Étage',
    min: 'Min',
    max: 'Max',
    room: 'Pièce',
    canton: "Canton",
    availability: "Disponibilité",
    from_date: "Partir de la date",
    immediately: "Immédiatement",
    charge: "Charge",
    choose: "Choisir",
    upload_changes: "Transférer les modifications",
    english_native: 'English',  
    french_native: 'Français',
    german_native: 'Deutsch',
    italian_native: 'Italiano',
    canton: 'Canton',
    profile: 'Profil',
    company:'Entreprise',
    create_company:'créer une entreprise',
    adress:'Adresse',
    basic_information:'Informations de base',
    company_name:'Nom de la compagnie',
    additional_address:'Adresse additionnelle',
    inbox_email:'Adresse email de la boîte de réception',
    short_name:"Nom abrégé de l'adresse électronique de la boîte de réception",
    additional_information:'Information additionnelle',
    contact_information:'Coordonnées',
    mobile_p:'Téléphone portable',
    website:'site Internet',
    fax:'fax',
    save_changes:'Sauvegarder les modifications',
    contacts:'Contacts',
    imp_exp:'Import/Export',
    new_contact:'Nouveau contact',
    all:'Tout',
    filter:'Filtre',
    marked:'Marqué comme supprimé',
    attributes:'Attributs',
    b_atributes:'Attributs de construction (facultatif)',
    more_photos:'Plus de photos',
    create_button:'Créer',
    upload_txt:"Téléchargez les photos du bâtiment ici. Si votre bâtiment comporte plusieurs unités, vous devez ajouter une unité individuelle au niveau de l'unité (étape ultérieure).",
    photo_property:'Photo de la propriété',
    property_type:'Type de propriété',
    number_of_units:"Nombre d'unités que vous possédez",
    unit_identification:"Identification de l'unité",
    add_new_property:'Ajouter nouvelle propriété',
    my_property:'Mes propriétés',
    pick_up:'Ramasser'




  },

  //german
  {
    app_title: "Gestimmo",
    step1: 'Schritt 1: Werbung',
    main_info: 'Hauptinformation',
    title_of_ad: 'Anzeigentitel',
    description: 'Beschreibung',
    country: 'Land',
    postcode:'Postleitzahl',
    postcode_and_city: 'Postleitzahl',
    street_and_house_number: 'Straße und Hausnummer',
    details: 'Einzelheiten',
    type_of_ownership: 'Art des Eigentums',
    for_rent: 'Zu vermieten',
    for_sale: 'Zu verkaufen',
    category: 'Kategorie',
    surface: 'Oberfläche',
    floor: 'Fußboden',
    rooms: 'Räume',
    invalid_date_format: 'Ungültiges Datumsformat',
    price_type: 'Preistyp',
    on_request: 'Auf Anfrage',
    price: 'Preis',
    back: 'Zurück',
    next: 'Nächster',
    step2: 'Schritt 2: Zusätzliche Details',
    near: 'Nahe',
    proximity: 'Nähe',
    facilities: 'Anlagen',
    outdoor_equipment: 'Outdoor Ausrüstung',
    interior_equipment: 'Innenausstattung',
    other_equipment: 'Andere Ausrüstung',
    soils: 'Böden',
    exposition: 'Exposition',
    views: 'Ansichten',
    sunshine: 'Sonnenschein',    
    step3: 'Schritt 3: Fotos',
    drop_some_files_here: 'Legen Sie einige Dateien hier ab!',
    or: 'oder',
    choose: 'Wählen',
    step4: 'Schritt 4: Kontaktinformationen',
    full_name: 'Vollständiger Name',
    phone_number: 'Telefonnummer',
    email: 'Email',
    compleated_all_the_steps: 'Sie haben alle Schritte abgeschlossen!',
    upload_ads: 'Anzeigen hochladen',
    confirm: 'Bestätigen',
    you_can_continue_from_the_previous_state: 'Sie können mit dem vorherigen Status fortfahren',
    yes: 'Ja',
    no: 'Nein',
    result: 'Ergebnis',
    load_more: 'Mehr laden',
    type: 'Art',
    rent: 'Miete',
    buy: 'Kaufen',
    property: 'Eigentum',
    city: 'Stadt',
    floor: 'Fußboden',
    min: 'Mindest',
    max: 'Max',
    room: 'Zimmer',
    canton: "Kanton",
    availability: "Verfügbarkeit",
    from_date: "Ab Datum",
    immediately: "Sofort",
    charge: "Aufladen",
    choose: "Wählen",
    upload_changes: "Änderungen hochladen",
    english_native: 'English',  
    french_native: 'Français',
    german_native: 'Deutsch',
    italian_native: 'Italiano',
    canton: 'Kanton',
    profile: 'Profil',
    company:'Unternehmen',
    create_company:'Firma gründen',
    adress:'Adresse',
    basic_information:'Grundinformation',
    company_name:'Name der Firma',
    additional_address:'zusätzliche Adresse',
    inbox_email:'E-Mail-Adresse des Posteingangs',
    short_name:'Kurzname für die E-Mail-Adresse des Posteingangs',
    additional_information:'Zusätzliche Information',
    contact_information:'Kontaktinformationen',
    mobile_p:'Mobiltelefon',
    website:'Webseite',
    fax:'Fax',
    save_changes:'Änderungen speichern',
    contacts:'Kontakte',
    imp_exp:'Import/Export',
    new_contact:'Neuer Kontakt',
    all:'Alles',
    filter:'Filter',
    marked:'Als gelöscht markiert',
    attributes:'Attribute',
    b_atributes:'Gebäudeattribute (optional)',
    more_photos:'Weitere Fotos',
    create_button:'Schaffen',
    upload_txt:'Laden Sie hier Gebäudefotos hoch. Wenn Ihr Gebäude über mehrere Einheiten verfügt, sollten einzelne Einheitenfotos zur Einheitenebene hinzugefügt werden (späterer Schritt).',
    photo_property:'Eigentum Foto',
    property_type:'Art der Eigentum',
    number_of_units:'Anzahl der Einheiten, die Sie besitzen',
    unit_identification:'Geräteidentifikation',
    add_new_property:'Neue Eigenschaft hinzufügen',
    my_property:'Meine Eigenschaften',
    pick_up:'Abholen'


  },

  //italian
  {
    app_title: "Gestimmo",
    step1: 'Passaggio 1: pubblicità',
    main_info: 'Informazione principale',
    title_of_ad: 'Titolo dell\'annuncio',
    description: 'Descrizione',
    country: 'Nazione',
    postcode: 'codice postale',
    street_and_house_number: 'Via e numero civico',
    details: 'Dettagli',
    type_of_ownership: 'Tipo di proprietà',
    for_rent: 'Da affittare',
    for_sale: 'In vendita',
    category: 'Categoria',
    surface: 'Superficie',
    floor: 'Pavimento',
    rooms: 'Camere',
    invalid_date_format: 'Formato data non valido',
    price_type: 'Tipo di prezzo',
    on_request: 'Su richiesta',
    price: 'Prezzo',
    back: 'Indietro',
    next: 'Il prossimo',
    step2: 'Passaggio 2: dettagli aggiuntivi',
    near: 'Vicino',
    proximity: 'Prossimità',
    facilities: 'Strutture',
    outdoor_equipment: 'Attrezzature da esterno',
    interior_equipment: 'Equipaggiamento interno',
    other_equipment: 'Altro equipaggiamento',
    soils: 'Suoli',
    exposition: 'Esposizione',
    views: 'Visualizzazioni',
    sunshine: 'Luce del sole',    
    step3: 'Passaggio 3: foto',
    drop_some_files_here: 'Rilascia alcuni file qui!',
    or: 'o',
    choose: 'Scegliere',
    step4: 'Passaggio 4: informazioni di contatto',
    full_name: 'Nome e cognome',
    phone_number: 'Numero di telefono',
    email: 'E-mail',
    compleated_all_the_steps: 'Hai completato tutti i passaggi!',
    upload_ads: 'Carica annunci',
    confirm: 'Confermare',
    you_can_continue_from_the_previous_state: 'Puoi continuare dallo stato precedente',
    yes: 'Si',
    no: 'No',
    result: 'Risultato',
    load_more: 'Carica di più',
    type: 'Genere',
    rent: 'Affitto',
    buy: 'Acquistare',
    property: 'Proprietà',
    city: 'Città',
    floor: 'Pavimento',
    min: 'Min',
    max: 'Max',
    room: 'Camera',
    canton: "Cantone",
    availability: "Disponibilità",
    from_date: "Dalla data",
    immediately: "Subito",
    charge: "Carica",
    choose: "Scegliere",
    upload_changes: "Carica modifiche",
    english_native: 'English',  
    french_native: 'Français',
    german_native: 'Deutsch',
    italian_native: 'Italiano',
    canton: 'Cantone',
    profile: 'Profilo',
    company:'Società',
    create_company:'creare società',
    adress:'Indirizzo',
    basic_information:'Informazioni di base',
    company_name:'Nome della ditta',
    additional_address:'Indirizzo aggiuntivo',
    inbox_email:'Indirizzo email in arrivo',
    short_name:"Nome breve per l'indirizzo e-mail in arrivo",
    additional_information:'Informazioni aggiuntive',
    contact_information:'Informazioni di contatto',
    mobile_p:'Cellulare',
    website:'sito web',
    fax:'Fax',
    save_changes:'Salva I Cambiamenti',
    contacts:'Contatti',
    imp_exp:'Import/Export',
    new_contact:'Nuovo contatto',
    all:'Tutti',
    filter:'Filtro',
    marked:'Contrassegnato come eliminato',
    attributes:'Attributi',
    b_atributes:'Attributi di costruzione (facoltativo)',
    more_photos:'Altre foto',
    create_button:'Create',
    upload_txt:"Carica qui le foto degli edifici. Se l'edificio ha più unità, le foto delle singole unità devono essere aggiunte a livello di unità (passaggio successivo).",
    photo_property:'Foto della proprietà',
    property_type:'Tipo di proprietà',
    number_of_units:'Numero di unità che possiedi',
    unit_identification:"Identificazione dell'unità",
    add_new_property:'Aggiungi nuova proprietà',
    my_property:'Le mie proprietà',
    pick_up:'Raccogliere'

  },
];

export default language;